
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StoryView` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model StoryView
 * 
 */
export type StoryViewModel = runtime.Types.Result.DefaultSelection<Prisma.$StoryViewPayload>

export type AggregateStoryView = {
  _count: StoryViewCountAggregateOutputType | null
  _min: StoryViewMinAggregateOutputType | null
  _max: StoryViewMaxAggregateOutputType | null
}

export type StoryViewMinAggregateOutputType = {
  id: string | null
  userId: string | null
  storyId: string | null
  viewedAt: Date | null
}

export type StoryViewMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  storyId: string | null
  viewedAt: Date | null
}

export type StoryViewCountAggregateOutputType = {
  id: number
  userId: number
  storyId: number
  viewedAt: number
  _all: number
}


export type StoryViewMinAggregateInputType = {
  id?: true
  userId?: true
  storyId?: true
  viewedAt?: true
}

export type StoryViewMaxAggregateInputType = {
  id?: true
  userId?: true
  storyId?: true
  viewedAt?: true
}

export type StoryViewCountAggregateInputType = {
  id?: true
  userId?: true
  storyId?: true
  viewedAt?: true
  _all?: true
}

export type StoryViewAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StoryView to aggregate.
   */
  where?: Prisma.StoryViewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoryViews to fetch.
   */
  orderBy?: Prisma.StoryViewOrderByWithRelationInput | Prisma.StoryViewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StoryViewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoryViews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoryViews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StoryViews
  **/
  _count?: true | StoryViewCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StoryViewMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StoryViewMaxAggregateInputType
}

export type GetStoryViewAggregateType<T extends StoryViewAggregateArgs> = {
      [P in keyof T & keyof AggregateStoryView]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStoryView[P]>
    : Prisma.GetScalarType<T[P], AggregateStoryView[P]>
}




export type StoryViewGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StoryViewWhereInput
  orderBy?: Prisma.StoryViewOrderByWithAggregationInput | Prisma.StoryViewOrderByWithAggregationInput[]
  by: Prisma.StoryViewScalarFieldEnum[] | Prisma.StoryViewScalarFieldEnum
  having?: Prisma.StoryViewScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StoryViewCountAggregateInputType | true
  _min?: StoryViewMinAggregateInputType
  _max?: StoryViewMaxAggregateInputType
}

export type StoryViewGroupByOutputType = {
  id: string
  userId: string
  storyId: string
  viewedAt: Date
  _count: StoryViewCountAggregateOutputType | null
  _min: StoryViewMinAggregateOutputType | null
  _max: StoryViewMaxAggregateOutputType | null
}

type GetStoryViewGroupByPayload<T extends StoryViewGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StoryViewGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StoryViewGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StoryViewGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StoryViewGroupByOutputType[P]>
      }
    >
  >



export type StoryViewWhereInput = {
  AND?: Prisma.StoryViewWhereInput | Prisma.StoryViewWhereInput[]
  OR?: Prisma.StoryViewWhereInput[]
  NOT?: Prisma.StoryViewWhereInput | Prisma.StoryViewWhereInput[]
  id?: Prisma.StringFilter<"StoryView"> | string
  userId?: Prisma.StringFilter<"StoryView"> | string
  storyId?: Prisma.StringFilter<"StoryView"> | string
  viewedAt?: Prisma.DateTimeFilter<"StoryView"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  story?: Prisma.XOR<Prisma.StoryScalarRelationFilter, Prisma.StoryWhereInput>
}

export type StoryViewOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  storyId?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  story?: Prisma.StoryOrderByWithRelationInput
}

export type StoryViewWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_storyId?: Prisma.StoryViewUserIdStoryIdCompoundUniqueInput
  AND?: Prisma.StoryViewWhereInput | Prisma.StoryViewWhereInput[]
  OR?: Prisma.StoryViewWhereInput[]
  NOT?: Prisma.StoryViewWhereInput | Prisma.StoryViewWhereInput[]
  userId?: Prisma.StringFilter<"StoryView"> | string
  storyId?: Prisma.StringFilter<"StoryView"> | string
  viewedAt?: Prisma.DateTimeFilter<"StoryView"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  story?: Prisma.XOR<Prisma.StoryScalarRelationFilter, Prisma.StoryWhereInput>
}, "id" | "userId_storyId">

export type StoryViewOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  storyId?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrder
  _count?: Prisma.StoryViewCountOrderByAggregateInput
  _max?: Prisma.StoryViewMaxOrderByAggregateInput
  _min?: Prisma.StoryViewMinOrderByAggregateInput
}

export type StoryViewScalarWhereWithAggregatesInput = {
  AND?: Prisma.StoryViewScalarWhereWithAggregatesInput | Prisma.StoryViewScalarWhereWithAggregatesInput[]
  OR?: Prisma.StoryViewScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StoryViewScalarWhereWithAggregatesInput | Prisma.StoryViewScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StoryView"> | string
  userId?: Prisma.StringWithAggregatesFilter<"StoryView"> | string
  storyId?: Prisma.StringWithAggregatesFilter<"StoryView"> | string
  viewedAt?: Prisma.DateTimeWithAggregatesFilter<"StoryView"> | Date | string
}

export type StoryViewCreateInput = {
  id?: string
  viewedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutStoryViewsInput
  story: Prisma.StoryCreateNestedOneWithoutViewsInput
}

export type StoryViewUncheckedCreateInput = {
  id?: string
  userId: string
  storyId: string
  viewedAt?: Date | string
}

export type StoryViewUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutStoryViewsNestedInput
  story?: Prisma.StoryUpdateOneRequiredWithoutViewsNestedInput
}

export type StoryViewUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  storyId?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoryViewCreateManyInput = {
  id?: string
  userId: string
  storyId: string
  viewedAt?: Date | string
}

export type StoryViewUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoryViewUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  storyId?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoryViewListRelationFilter = {
  every?: Prisma.StoryViewWhereInput
  some?: Prisma.StoryViewWhereInput
  none?: Prisma.StoryViewWhereInput
}

export type StoryViewOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StoryViewUserIdStoryIdCompoundUniqueInput = {
  userId: string
  storyId: string
}

export type StoryViewCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  storyId?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrder
}

export type StoryViewMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  storyId?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrder
}

export type StoryViewMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  storyId?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrder
}

export type StoryViewCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StoryViewCreateWithoutUserInput, Prisma.StoryViewUncheckedCreateWithoutUserInput> | Prisma.StoryViewCreateWithoutUserInput[] | Prisma.StoryViewUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StoryViewCreateOrConnectWithoutUserInput | Prisma.StoryViewCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StoryViewCreateManyUserInputEnvelope
  connect?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
}

export type StoryViewUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StoryViewCreateWithoutUserInput, Prisma.StoryViewUncheckedCreateWithoutUserInput> | Prisma.StoryViewCreateWithoutUserInput[] | Prisma.StoryViewUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StoryViewCreateOrConnectWithoutUserInput | Prisma.StoryViewCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StoryViewCreateManyUserInputEnvelope
  connect?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
}

export type StoryViewUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StoryViewCreateWithoutUserInput, Prisma.StoryViewUncheckedCreateWithoutUserInput> | Prisma.StoryViewCreateWithoutUserInput[] | Prisma.StoryViewUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StoryViewCreateOrConnectWithoutUserInput | Prisma.StoryViewCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StoryViewUpsertWithWhereUniqueWithoutUserInput | Prisma.StoryViewUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StoryViewCreateManyUserInputEnvelope
  set?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  disconnect?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  delete?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  connect?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  update?: Prisma.StoryViewUpdateWithWhereUniqueWithoutUserInput | Prisma.StoryViewUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StoryViewUpdateManyWithWhereWithoutUserInput | Prisma.StoryViewUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StoryViewScalarWhereInput | Prisma.StoryViewScalarWhereInput[]
}

export type StoryViewUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StoryViewCreateWithoutUserInput, Prisma.StoryViewUncheckedCreateWithoutUserInput> | Prisma.StoryViewCreateWithoutUserInput[] | Prisma.StoryViewUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StoryViewCreateOrConnectWithoutUserInput | Prisma.StoryViewCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StoryViewUpsertWithWhereUniqueWithoutUserInput | Prisma.StoryViewUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StoryViewCreateManyUserInputEnvelope
  set?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  disconnect?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  delete?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  connect?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  update?: Prisma.StoryViewUpdateWithWhereUniqueWithoutUserInput | Prisma.StoryViewUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StoryViewUpdateManyWithWhereWithoutUserInput | Prisma.StoryViewUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StoryViewScalarWhereInput | Prisma.StoryViewScalarWhereInput[]
}

export type StoryViewCreateNestedManyWithoutStoryInput = {
  create?: Prisma.XOR<Prisma.StoryViewCreateWithoutStoryInput, Prisma.StoryViewUncheckedCreateWithoutStoryInput> | Prisma.StoryViewCreateWithoutStoryInput[] | Prisma.StoryViewUncheckedCreateWithoutStoryInput[]
  connectOrCreate?: Prisma.StoryViewCreateOrConnectWithoutStoryInput | Prisma.StoryViewCreateOrConnectWithoutStoryInput[]
  createMany?: Prisma.StoryViewCreateManyStoryInputEnvelope
  connect?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
}

export type StoryViewUncheckedCreateNestedManyWithoutStoryInput = {
  create?: Prisma.XOR<Prisma.StoryViewCreateWithoutStoryInput, Prisma.StoryViewUncheckedCreateWithoutStoryInput> | Prisma.StoryViewCreateWithoutStoryInput[] | Prisma.StoryViewUncheckedCreateWithoutStoryInput[]
  connectOrCreate?: Prisma.StoryViewCreateOrConnectWithoutStoryInput | Prisma.StoryViewCreateOrConnectWithoutStoryInput[]
  createMany?: Prisma.StoryViewCreateManyStoryInputEnvelope
  connect?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
}

export type StoryViewUpdateManyWithoutStoryNestedInput = {
  create?: Prisma.XOR<Prisma.StoryViewCreateWithoutStoryInput, Prisma.StoryViewUncheckedCreateWithoutStoryInput> | Prisma.StoryViewCreateWithoutStoryInput[] | Prisma.StoryViewUncheckedCreateWithoutStoryInput[]
  connectOrCreate?: Prisma.StoryViewCreateOrConnectWithoutStoryInput | Prisma.StoryViewCreateOrConnectWithoutStoryInput[]
  upsert?: Prisma.StoryViewUpsertWithWhereUniqueWithoutStoryInput | Prisma.StoryViewUpsertWithWhereUniqueWithoutStoryInput[]
  createMany?: Prisma.StoryViewCreateManyStoryInputEnvelope
  set?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  disconnect?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  delete?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  connect?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  update?: Prisma.StoryViewUpdateWithWhereUniqueWithoutStoryInput | Prisma.StoryViewUpdateWithWhereUniqueWithoutStoryInput[]
  updateMany?: Prisma.StoryViewUpdateManyWithWhereWithoutStoryInput | Prisma.StoryViewUpdateManyWithWhereWithoutStoryInput[]
  deleteMany?: Prisma.StoryViewScalarWhereInput | Prisma.StoryViewScalarWhereInput[]
}

export type StoryViewUncheckedUpdateManyWithoutStoryNestedInput = {
  create?: Prisma.XOR<Prisma.StoryViewCreateWithoutStoryInput, Prisma.StoryViewUncheckedCreateWithoutStoryInput> | Prisma.StoryViewCreateWithoutStoryInput[] | Prisma.StoryViewUncheckedCreateWithoutStoryInput[]
  connectOrCreate?: Prisma.StoryViewCreateOrConnectWithoutStoryInput | Prisma.StoryViewCreateOrConnectWithoutStoryInput[]
  upsert?: Prisma.StoryViewUpsertWithWhereUniqueWithoutStoryInput | Prisma.StoryViewUpsertWithWhereUniqueWithoutStoryInput[]
  createMany?: Prisma.StoryViewCreateManyStoryInputEnvelope
  set?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  disconnect?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  delete?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  connect?: Prisma.StoryViewWhereUniqueInput | Prisma.StoryViewWhereUniqueInput[]
  update?: Prisma.StoryViewUpdateWithWhereUniqueWithoutStoryInput | Prisma.StoryViewUpdateWithWhereUniqueWithoutStoryInput[]
  updateMany?: Prisma.StoryViewUpdateManyWithWhereWithoutStoryInput | Prisma.StoryViewUpdateManyWithWhereWithoutStoryInput[]
  deleteMany?: Prisma.StoryViewScalarWhereInput | Prisma.StoryViewScalarWhereInput[]
}

export type StoryViewCreateWithoutUserInput = {
  id?: string
  viewedAt?: Date | string
  story: Prisma.StoryCreateNestedOneWithoutViewsInput
}

export type StoryViewUncheckedCreateWithoutUserInput = {
  id?: string
  storyId: string
  viewedAt?: Date | string
}

export type StoryViewCreateOrConnectWithoutUserInput = {
  where: Prisma.StoryViewWhereUniqueInput
  create: Prisma.XOR<Prisma.StoryViewCreateWithoutUserInput, Prisma.StoryViewUncheckedCreateWithoutUserInput>
}

export type StoryViewCreateManyUserInputEnvelope = {
  data: Prisma.StoryViewCreateManyUserInput | Prisma.StoryViewCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type StoryViewUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.StoryViewWhereUniqueInput
  update: Prisma.XOR<Prisma.StoryViewUpdateWithoutUserInput, Prisma.StoryViewUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.StoryViewCreateWithoutUserInput, Prisma.StoryViewUncheckedCreateWithoutUserInput>
}

export type StoryViewUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.StoryViewWhereUniqueInput
  data: Prisma.XOR<Prisma.StoryViewUpdateWithoutUserInput, Prisma.StoryViewUncheckedUpdateWithoutUserInput>
}

export type StoryViewUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.StoryViewScalarWhereInput
  data: Prisma.XOR<Prisma.StoryViewUpdateManyMutationInput, Prisma.StoryViewUncheckedUpdateManyWithoutUserInput>
}

export type StoryViewScalarWhereInput = {
  AND?: Prisma.StoryViewScalarWhereInput | Prisma.StoryViewScalarWhereInput[]
  OR?: Prisma.StoryViewScalarWhereInput[]
  NOT?: Prisma.StoryViewScalarWhereInput | Prisma.StoryViewScalarWhereInput[]
  id?: Prisma.StringFilter<"StoryView"> | string
  userId?: Prisma.StringFilter<"StoryView"> | string
  storyId?: Prisma.StringFilter<"StoryView"> | string
  viewedAt?: Prisma.DateTimeFilter<"StoryView"> | Date | string
}

export type StoryViewCreateWithoutStoryInput = {
  id?: string
  viewedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutStoryViewsInput
}

export type StoryViewUncheckedCreateWithoutStoryInput = {
  id?: string
  userId: string
  viewedAt?: Date | string
}

export type StoryViewCreateOrConnectWithoutStoryInput = {
  where: Prisma.StoryViewWhereUniqueInput
  create: Prisma.XOR<Prisma.StoryViewCreateWithoutStoryInput, Prisma.StoryViewUncheckedCreateWithoutStoryInput>
}

export type StoryViewCreateManyStoryInputEnvelope = {
  data: Prisma.StoryViewCreateManyStoryInput | Prisma.StoryViewCreateManyStoryInput[]
  skipDuplicates?: boolean
}

export type StoryViewUpsertWithWhereUniqueWithoutStoryInput = {
  where: Prisma.StoryViewWhereUniqueInput
  update: Prisma.XOR<Prisma.StoryViewUpdateWithoutStoryInput, Prisma.StoryViewUncheckedUpdateWithoutStoryInput>
  create: Prisma.XOR<Prisma.StoryViewCreateWithoutStoryInput, Prisma.StoryViewUncheckedCreateWithoutStoryInput>
}

export type StoryViewUpdateWithWhereUniqueWithoutStoryInput = {
  where: Prisma.StoryViewWhereUniqueInput
  data: Prisma.XOR<Prisma.StoryViewUpdateWithoutStoryInput, Prisma.StoryViewUncheckedUpdateWithoutStoryInput>
}

export type StoryViewUpdateManyWithWhereWithoutStoryInput = {
  where: Prisma.StoryViewScalarWhereInput
  data: Prisma.XOR<Prisma.StoryViewUpdateManyMutationInput, Prisma.StoryViewUncheckedUpdateManyWithoutStoryInput>
}

export type StoryViewCreateManyUserInput = {
  id?: string
  storyId: string
  viewedAt?: Date | string
}

export type StoryViewUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  story?: Prisma.StoryUpdateOneRequiredWithoutViewsNestedInput
}

export type StoryViewUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  storyId?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoryViewUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  storyId?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoryViewCreateManyStoryInput = {
  id?: string
  userId: string
  viewedAt?: Date | string
}

export type StoryViewUpdateWithoutStoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutStoryViewsNestedInput
}

export type StoryViewUncheckedUpdateWithoutStoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoryViewUncheckedUpdateManyWithoutStoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type StoryViewSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  storyId?: boolean
  viewedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  story?: boolean | Prisma.StoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["storyView"]>

export type StoryViewSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  storyId?: boolean
  viewedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  story?: boolean | Prisma.StoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["storyView"]>

export type StoryViewSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  storyId?: boolean
  viewedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  story?: boolean | Prisma.StoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["storyView"]>

export type StoryViewSelectScalar = {
  id?: boolean
  userId?: boolean
  storyId?: boolean
  viewedAt?: boolean
}

export type StoryViewOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "storyId" | "viewedAt", ExtArgs["result"]["storyView"]>
export type StoryViewInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  story?: boolean | Prisma.StoryDefaultArgs<ExtArgs>
}
export type StoryViewIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  story?: boolean | Prisma.StoryDefaultArgs<ExtArgs>
}
export type StoryViewIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  story?: boolean | Prisma.StoryDefaultArgs<ExtArgs>
}

export type $StoryViewPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StoryView"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    story: Prisma.$StoryPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    storyId: string
    viewedAt: Date
  }, ExtArgs["result"]["storyView"]>
  composites: {}
}

export type StoryViewGetPayload<S extends boolean | null | undefined | StoryViewDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StoryViewPayload, S>

export type StoryViewCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StoryViewFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StoryViewCountAggregateInputType | true
  }

export interface StoryViewDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StoryView'], meta: { name: 'StoryView' } }
  /**
   * Find zero or one StoryView that matches the filter.
   * @param {StoryViewFindUniqueArgs} args - Arguments to find a StoryView
   * @example
   * // Get one StoryView
   * const storyView = await prisma.storyView.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StoryViewFindUniqueArgs>(args: Prisma.SelectSubset<T, StoryViewFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StoryViewClient<runtime.Types.Result.GetResult<Prisma.$StoryViewPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StoryView that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StoryViewFindUniqueOrThrowArgs} args - Arguments to find a StoryView
   * @example
   * // Get one StoryView
   * const storyView = await prisma.storyView.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StoryViewFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StoryViewFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StoryViewClient<runtime.Types.Result.GetResult<Prisma.$StoryViewPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StoryView that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoryViewFindFirstArgs} args - Arguments to find a StoryView
   * @example
   * // Get one StoryView
   * const storyView = await prisma.storyView.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StoryViewFindFirstArgs>(args?: Prisma.SelectSubset<T, StoryViewFindFirstArgs<ExtArgs>>): Prisma.Prisma__StoryViewClient<runtime.Types.Result.GetResult<Prisma.$StoryViewPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StoryView that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoryViewFindFirstOrThrowArgs} args - Arguments to find a StoryView
   * @example
   * // Get one StoryView
   * const storyView = await prisma.storyView.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StoryViewFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StoryViewFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StoryViewClient<runtime.Types.Result.GetResult<Prisma.$StoryViewPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StoryViews that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoryViewFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StoryViews
   * const storyViews = await prisma.storyView.findMany()
   * 
   * // Get first 10 StoryViews
   * const storyViews = await prisma.storyView.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const storyViewWithIdOnly = await prisma.storyView.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StoryViewFindManyArgs>(args?: Prisma.SelectSubset<T, StoryViewFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StoryViewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StoryView.
   * @param {StoryViewCreateArgs} args - Arguments to create a StoryView.
   * @example
   * // Create one StoryView
   * const StoryView = await prisma.storyView.create({
   *   data: {
   *     // ... data to create a StoryView
   *   }
   * })
   * 
   */
  create<T extends StoryViewCreateArgs>(args: Prisma.SelectSubset<T, StoryViewCreateArgs<ExtArgs>>): Prisma.Prisma__StoryViewClient<runtime.Types.Result.GetResult<Prisma.$StoryViewPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StoryViews.
   * @param {StoryViewCreateManyArgs} args - Arguments to create many StoryViews.
   * @example
   * // Create many StoryViews
   * const storyView = await prisma.storyView.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StoryViewCreateManyArgs>(args?: Prisma.SelectSubset<T, StoryViewCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StoryViews and returns the data saved in the database.
   * @param {StoryViewCreateManyAndReturnArgs} args - Arguments to create many StoryViews.
   * @example
   * // Create many StoryViews
   * const storyView = await prisma.storyView.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StoryViews and only return the `id`
   * const storyViewWithIdOnly = await prisma.storyView.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StoryViewCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StoryViewCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StoryViewPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StoryView.
   * @param {StoryViewDeleteArgs} args - Arguments to delete one StoryView.
   * @example
   * // Delete one StoryView
   * const StoryView = await prisma.storyView.delete({
   *   where: {
   *     // ... filter to delete one StoryView
   *   }
   * })
   * 
   */
  delete<T extends StoryViewDeleteArgs>(args: Prisma.SelectSubset<T, StoryViewDeleteArgs<ExtArgs>>): Prisma.Prisma__StoryViewClient<runtime.Types.Result.GetResult<Prisma.$StoryViewPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StoryView.
   * @param {StoryViewUpdateArgs} args - Arguments to update one StoryView.
   * @example
   * // Update one StoryView
   * const storyView = await prisma.storyView.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StoryViewUpdateArgs>(args: Prisma.SelectSubset<T, StoryViewUpdateArgs<ExtArgs>>): Prisma.Prisma__StoryViewClient<runtime.Types.Result.GetResult<Prisma.$StoryViewPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StoryViews.
   * @param {StoryViewDeleteManyArgs} args - Arguments to filter StoryViews to delete.
   * @example
   * // Delete a few StoryViews
   * const { count } = await prisma.storyView.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StoryViewDeleteManyArgs>(args?: Prisma.SelectSubset<T, StoryViewDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StoryViews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoryViewUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StoryViews
   * const storyView = await prisma.storyView.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StoryViewUpdateManyArgs>(args: Prisma.SelectSubset<T, StoryViewUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StoryViews and returns the data updated in the database.
   * @param {StoryViewUpdateManyAndReturnArgs} args - Arguments to update many StoryViews.
   * @example
   * // Update many StoryViews
   * const storyView = await prisma.storyView.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StoryViews and only return the `id`
   * const storyViewWithIdOnly = await prisma.storyView.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StoryViewUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StoryViewUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StoryViewPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StoryView.
   * @param {StoryViewUpsertArgs} args - Arguments to update or create a StoryView.
   * @example
   * // Update or create a StoryView
   * const storyView = await prisma.storyView.upsert({
   *   create: {
   *     // ... data to create a StoryView
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StoryView we want to update
   *   }
   * })
   */
  upsert<T extends StoryViewUpsertArgs>(args: Prisma.SelectSubset<T, StoryViewUpsertArgs<ExtArgs>>): Prisma.Prisma__StoryViewClient<runtime.Types.Result.GetResult<Prisma.$StoryViewPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StoryViews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoryViewCountArgs} args - Arguments to filter StoryViews to count.
   * @example
   * // Count the number of StoryViews
   * const count = await prisma.storyView.count({
   *   where: {
   *     // ... the filter for the StoryViews we want to count
   *   }
   * })
  **/
  count<T extends StoryViewCountArgs>(
    args?: Prisma.Subset<T, StoryViewCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StoryViewCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StoryView.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoryViewAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StoryViewAggregateArgs>(args: Prisma.Subset<T, StoryViewAggregateArgs>): Prisma.PrismaPromise<GetStoryViewAggregateType<T>>

  /**
   * Group by StoryView.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoryViewGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StoryViewGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StoryViewGroupByArgs['orderBy'] }
      : { orderBy?: StoryViewGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StoryViewGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStoryViewGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StoryView model
 */
readonly fields: StoryViewFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StoryView.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StoryViewClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  story<T extends Prisma.StoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StoryDefaultArgs<ExtArgs>>): Prisma.Prisma__StoryClient<runtime.Types.Result.GetResult<Prisma.$StoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StoryView model
 */
export interface StoryViewFieldRefs {
  readonly id: Prisma.FieldRef<"StoryView", 'String'>
  readonly userId: Prisma.FieldRef<"StoryView", 'String'>
  readonly storyId: Prisma.FieldRef<"StoryView", 'String'>
  readonly viewedAt: Prisma.FieldRef<"StoryView", 'DateTime'>
}
    

// Custom InputTypes
/**
 * StoryView findUnique
 */
export type StoryViewFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoryView
   */
  select?: Prisma.StoryViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoryView
   */
  omit?: Prisma.StoryViewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoryViewInclude<ExtArgs> | null
  /**
   * Filter, which StoryView to fetch.
   */
  where: Prisma.StoryViewWhereUniqueInput
}

/**
 * StoryView findUniqueOrThrow
 */
export type StoryViewFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoryView
   */
  select?: Prisma.StoryViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoryView
   */
  omit?: Prisma.StoryViewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoryViewInclude<ExtArgs> | null
  /**
   * Filter, which StoryView to fetch.
   */
  where: Prisma.StoryViewWhereUniqueInput
}

/**
 * StoryView findFirst
 */
export type StoryViewFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoryView
   */
  select?: Prisma.StoryViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoryView
   */
  omit?: Prisma.StoryViewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoryViewInclude<ExtArgs> | null
  /**
   * Filter, which StoryView to fetch.
   */
  where?: Prisma.StoryViewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoryViews to fetch.
   */
  orderBy?: Prisma.StoryViewOrderByWithRelationInput | Prisma.StoryViewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StoryViews.
   */
  cursor?: Prisma.StoryViewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoryViews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoryViews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StoryViews.
   */
  distinct?: Prisma.StoryViewScalarFieldEnum | Prisma.StoryViewScalarFieldEnum[]
}

/**
 * StoryView findFirstOrThrow
 */
export type StoryViewFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoryView
   */
  select?: Prisma.StoryViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoryView
   */
  omit?: Prisma.StoryViewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoryViewInclude<ExtArgs> | null
  /**
   * Filter, which StoryView to fetch.
   */
  where?: Prisma.StoryViewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoryViews to fetch.
   */
  orderBy?: Prisma.StoryViewOrderByWithRelationInput | Prisma.StoryViewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StoryViews.
   */
  cursor?: Prisma.StoryViewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoryViews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoryViews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StoryViews.
   */
  distinct?: Prisma.StoryViewScalarFieldEnum | Prisma.StoryViewScalarFieldEnum[]
}

/**
 * StoryView findMany
 */
export type StoryViewFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoryView
   */
  select?: Prisma.StoryViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoryView
   */
  omit?: Prisma.StoryViewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoryViewInclude<ExtArgs> | null
  /**
   * Filter, which StoryViews to fetch.
   */
  where?: Prisma.StoryViewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoryViews to fetch.
   */
  orderBy?: Prisma.StoryViewOrderByWithRelationInput | Prisma.StoryViewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StoryViews.
   */
  cursor?: Prisma.StoryViewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoryViews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoryViews.
   */
  skip?: number
  distinct?: Prisma.StoryViewScalarFieldEnum | Prisma.StoryViewScalarFieldEnum[]
}

/**
 * StoryView create
 */
export type StoryViewCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoryView
   */
  select?: Prisma.StoryViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoryView
   */
  omit?: Prisma.StoryViewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoryViewInclude<ExtArgs> | null
  /**
   * The data needed to create a StoryView.
   */
  data: Prisma.XOR<Prisma.StoryViewCreateInput, Prisma.StoryViewUncheckedCreateInput>
}

/**
 * StoryView createMany
 */
export type StoryViewCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StoryViews.
   */
  data: Prisma.StoryViewCreateManyInput | Prisma.StoryViewCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StoryView createManyAndReturn
 */
export type StoryViewCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoryView
   */
  select?: Prisma.StoryViewSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StoryView
   */
  omit?: Prisma.StoryViewOmit<ExtArgs> | null
  /**
   * The data used to create many StoryViews.
   */
  data: Prisma.StoryViewCreateManyInput | Prisma.StoryViewCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoryViewIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StoryView update
 */
export type StoryViewUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoryView
   */
  select?: Prisma.StoryViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoryView
   */
  omit?: Prisma.StoryViewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoryViewInclude<ExtArgs> | null
  /**
   * The data needed to update a StoryView.
   */
  data: Prisma.XOR<Prisma.StoryViewUpdateInput, Prisma.StoryViewUncheckedUpdateInput>
  /**
   * Choose, which StoryView to update.
   */
  where: Prisma.StoryViewWhereUniqueInput
}

/**
 * StoryView updateMany
 */
export type StoryViewUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StoryViews.
   */
  data: Prisma.XOR<Prisma.StoryViewUpdateManyMutationInput, Prisma.StoryViewUncheckedUpdateManyInput>
  /**
   * Filter which StoryViews to update
   */
  where?: Prisma.StoryViewWhereInput
  /**
   * Limit how many StoryViews to update.
   */
  limit?: number
}

/**
 * StoryView updateManyAndReturn
 */
export type StoryViewUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoryView
   */
  select?: Prisma.StoryViewSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StoryView
   */
  omit?: Prisma.StoryViewOmit<ExtArgs> | null
  /**
   * The data used to update StoryViews.
   */
  data: Prisma.XOR<Prisma.StoryViewUpdateManyMutationInput, Prisma.StoryViewUncheckedUpdateManyInput>
  /**
   * Filter which StoryViews to update
   */
  where?: Prisma.StoryViewWhereInput
  /**
   * Limit how many StoryViews to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoryViewIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StoryView upsert
 */
export type StoryViewUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoryView
   */
  select?: Prisma.StoryViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoryView
   */
  omit?: Prisma.StoryViewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoryViewInclude<ExtArgs> | null
  /**
   * The filter to search for the StoryView to update in case it exists.
   */
  where: Prisma.StoryViewWhereUniqueInput
  /**
   * In case the StoryView found by the `where` argument doesn't exist, create a new StoryView with this data.
   */
  create: Prisma.XOR<Prisma.StoryViewCreateInput, Prisma.StoryViewUncheckedCreateInput>
  /**
   * In case the StoryView was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StoryViewUpdateInput, Prisma.StoryViewUncheckedUpdateInput>
}

/**
 * StoryView delete
 */
export type StoryViewDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoryView
   */
  select?: Prisma.StoryViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoryView
   */
  omit?: Prisma.StoryViewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoryViewInclude<ExtArgs> | null
  /**
   * Filter which StoryView to delete.
   */
  where: Prisma.StoryViewWhereUniqueInput
}

/**
 * StoryView deleteMany
 */
export type StoryViewDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StoryViews to delete
   */
  where?: Prisma.StoryViewWhereInput
  /**
   * Limit how many StoryViews to delete.
   */
  limit?: number
}

/**
 * StoryView without action
 */
export type StoryViewDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoryView
   */
  select?: Prisma.StoryViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoryView
   */
  omit?: Prisma.StoryViewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoryViewInclude<ExtArgs> | null
}
